### ISSUE TITLE
Problem with "patch" on Windows 7 Sublime Text 3

### ISSUE THREAD

**Issue by vukanac** [lucacri/PhpSimpleRefactor#9]
Getting error:

**Sublime Text:**

```
patch: **** Only garbage was found in the patch input.
```

I had:
1. Add `d:\bin` to PATH
2. Place `refactor.phar` and `refactor.bat` in `d:\bin`
3. test in terminal with file: `Sample.php`

``` php
class Sample
{
    public function calculate($a, $b, $op)
    {
        if ($op == '+') {
            $result = $a + $b;
        }
        return $result;
    }
}
```

`$refactor extract-method Sample.php 7-7 sum`

gives output:

```
--- a/Sample.php
+++ b/Sample.php
@@ -4,8 +4,15 @@
     public function calculate($a, $b, $op)
     {
         if ($op == '+') {
-            $result = $a + $b;
+            $result = $this->sum($a, $b);
         }
         return $result;
     }
+
+    private function sum($a, $b)
+    {
+        $result = $a + $b;
+
+        return $result;
+    }
 }
```

and **nothitng is changed in file**.
1. Sublime Text 3083
2. Package Controll: Instal Package > PhpSimpleRefactor
3. Fill user.settings:

```
/** FILE: PHPSimpleRefactor.sublime-settings **/
{
    "php_path" : "d:\\wamp\\bin\\php\\php5.5.12\\php.exe",
    "refactor_path" : "d:\\bin\\refactor.bat" 
}
```

On same file produce error:

**Sublime Text:**
    patch: ***\* Only garbage was found in the patch input.

**Comment by vukanac** [comment]
When change `.bat` to `.phar`

```
/** FILE: PHPSimpleRefactor.sublime-settings **/
{
    "php_path" : "d:\\wamp\\bin\\php\\php5.5.12\\php.exe",
    "refactor_path" : "d:\\bin\\refactor.phar" 
}
```

Sublime produce 2 new file and **does not change original file**.
- `Sample.php.orig` - excact copy of original file = Sample.php
- `Sample.php.rej` - diff output like above in terminal

Is it posible to have chages applied to original file?

**Comment by lucacri** [comment]
sorry, i'm not maintaining this package anymore. Anyone that can help @vukanac ?

**Comment by vukanac** [comment]
Solved by installing `patch` for windows. Added it in in folder within PATH. In my case `d:\bin\`.

Now it works.

In addition - refactoring of methods only works inside other method (class > function), and cannot be used in plain/procedural php file.
